### PR TITLE
Nico's Details

### PR DESCRIPTION
**Pull request by nicobokhari13**

### CODE REVIEW

**Comment by nicobokhari13** [comment]
LGTM lol

**Comment by andyblarblar** [comment]
Here's a challenge for you before we merge this. Notice how you have two small commits, try merging them into a single commit and updating this PR likewise. If you don't remember how to do this, it was covered near the end of the presentation.

Good luck!

**Comment by andyblarblar** [comment]
Ah, I am afraid you have fallen into the classic trap of rebasing commits you haven't worked on. I'm afraid I wont be able to merge this (like, actually, not just for play), because the older commits will now conflict. Ngl, I think you may need to reset your branch and recommit for this to work, since idk another way to restore the old commits ngl

**Comment by nicobokhari13** [comment]
> Ah, I am afraid you have fallen into the classic trap of rebasing commits you haven't worked on. I'm afraid I wont be able to merge this (like, actually, not just for play), because the older commits will now conflict. Ngl, I think you may need to reset your branch and recommit for this to work, since idk another way to restore the old commits ngl

So would I run: 
git fetch origin
git reset --hard origin/master

to completely reset to my local to isc's LearningGit 

Or is there an easier way to reset to before my squashed commit?

**Comment by nicobokhari13** [comment]
I think I figured it out? 

I reset my local details branch to an earlier commit. 
Made some changes, and committed them. 
Rebased the two commits. 
Force push onto origin.

**Comment by andyblarblar** [comment]
> I think I figured it out?
> 
> I reset my local details branch to an earlier commit. Made some changes, and committed them. Rebased the two commits. Force push onto origin.

Yep! That's exactly what to do. I can't tell you the amount of times I've had to do this lol. In the future, check the git log of your local before force pushing, so if you made a mistake like here you can just reset to your fork instead of redoing all the work.

**Pull request merged**
